global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'anomaly-analyzer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
#  - job_name: 'anomaly-analyzer'
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: ['temperature-anomaly-analyzer:80']
