{
 "title": "temperature anomaly analyzer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "detecting anomalies average processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(anomaly_detecting_seconds_sum) / rate(anomaly_detecting_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "how fast anomalies appears in time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(detected_anomalies_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max consuming time from temperature_measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(temperature_measurement_consuming_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}