apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
    uid: ednzguuirn8xse
